[package]
name = "cargo-ui"
version = "0.2.0"
authors = ["SixtyFPS <info@sixtyfps.io>"]
edition = "2018"
build = "build.rs"
license = "GPL-3.0-only"
description = "GUI for cargo"
categories = ["development-tools::cargo-plugins"]
keywords = ["cargo", "ui", "gui"]
repository = "https://github.com/sixtyfpsui/cargo-ui"
resolver = "2"

[features]
x11 = ["sixtyfps/x11"]
wayland = ["sixtyfps/wayland"]
sixtyfps-backend-qt = ["sixtyfps/backend-qt"]
sixtyfps-backend-gl = ["sixtyfps/backend-qt"]
vendored-openssl = ["git2/vendored-openssl"]
default = ["x11", "wayland", "sixtyfps-backend-qt", "sixtyfps-backend-gl"]

[dependencies]
sixtyfps = { version = "0.1.3", default-features = false }
tokio = { version = "1", features= ["full"] }
futures = "0.3"
cargo_metadata = "0.14"
serde_json = "1"
serde = "1"
dunce = "1"
itertools = "0.10"
shlex = "1"
open = "2"
crates-index = "0.17"
toml_edit = "0.5"
anyhow = "1"
git2 = "0.13.23"

[target.'cfg(any(target_os = "macos", target_os = "windows"))'.dependencies]
rfd = "0.4.0"

[target.'cfg(not(any(target_os = "macos", target_os = "windows")))'.dependencies]
dialog = "0.3"

[build-dependencies]
sixtyfps-build = "0.1.3"

