[package]
name = "cargo-ui"
version = "0.2.0"
authors = ["SixtyFPS <info@sixtyfps.io>"]
edition = "2018"
build = "build.rs"
license = "GPL-3.0-only"
description = "GUI for cargo"
categories = ["development-tools::cargo-plugins"]
keywords = ["cargo", "ui", "gui"]
repository = "https://github.com/sixtyfpsui/cargo-ui"
resolver = "2"

[features]
x11 = ["sixtyfps/x11"]
wayland = ["sixtyfps/wayland"]
sixtyfps-backend-qt = ["sixtyfps/backend-qt"]
sixtyfps-backend-gl = ["sixtyfps/backend-qt"]
default = ["x11", "wayland", "sixtyfps-backend-qt", "sixtyfps-backend-gl"]

[dependencies]
sixtyfps = { version = "0.1.3", default-features = false, git = "https://github.com/sixtyfpsui/sixtyfps", branch = "master" }
tokio = { version = "1.12.0", features= ["full"] }
futures = "0.3"
cargo_metadata = "0.14"
serde_json = "1"
serde = "1"
dunce = "1"
itertools = "0.10"
shlex = "1"
open = "2"
crates-index = { version = "0.18.0" }
toml_edit = "0.6.0"
anyhow = "1"

[target.'cfg(any(target_os = "macos", target_os = "windows"))'.dependencies]
rfd = "0.5.1"

[target.'cfg(not(any(target_os = "macos", target_os = "windows")))'.dependencies]
dialog = "0.3"

[build-dependencies]
sixtyfps-build = { version = "0.1.3", git = "https://github.com/sixtyfpsui/sixtyfps", branch = "master" }

