[package]
name = "cargo-ui"
version = "0.1.0"
authors = ["SixtyFPS <info@sixtyfps.io>"]
edition = "2018"
build = "build.rs"
license = "GPL-3.0-only"
description = "GUI for cargo"
categories = ["development-tools::cargo-plugins"]
keywords = ["cargo", "ui", "gui"]
repository = "https://github.com/sixtyfpsui/cargo-ui"
resolver = "2"

[dependencies]
sixtyfps = "0.1.2"
tokio = { version = "1", features= ["full"] }
cargo_metadata = "0.14"
serde_json = "1"
serde = "1"
dunce = "1"
itertools = "0.10"

[target.'cfg(any(target_os = "macos", target_os = "windows"))'.dependencies]
rfd = "0.4.0"

[target.'cfg(not(any(target_os = "macos", target_os = "windows")))'.dependencies]
dialog = "0.3"

[build-dependencies]
sixtyfps-build = "0.1.2"

# Needed to avoid panic when using tab widget: https://github.com/sixtyfpsui/sixtyfps/issues/412
[patch.crates-io]
sixtyfps = { git = "https://github.com/sixtyfpsui/sixtyfps", rev = "5fc5563c992a36d618bcb29ac780d2cfd359b5aa" }
sixtyfps-build = { git = "https://github.com/sixtyfpsui/sixtyfps", rev = "5fc5563c992a36d618bcb29ac780d2cfd359b5aa" }
