name: Build cargo-ui binary

on:
  workflow_dispatch:
    inputs:
      host_os:
        description: "GH actions host os name (ubuntu-latest, etc.)"
        default: "ubuntu-latest"
        required: false
        type: string
      rust_target:
        description: "Rust target triple (x86_64-unknown-linux-gnu, etc.)"
        default: "x86_64-unknown-linux-gnu"
        required: false
        type: string      
      artifact_name:
        description: "Name of the GH action artifact to upload"
        default: "cargo-ui-linux"
        required: false
        type: string
      qt_version:
        description: "Qt version to install"
        default: "5.15.2"
        required: false
        type: string
  workflow_call:
    inputs:
      host_os:
        description: "GH actions host os name (ubuntu-latest, etc.)"
        default: "ubuntu-latest"
        required: false
        type: string
      rust_target:
        description: "Rust target triple (x86_64-unknown-linux-gnu, etc.)"
        default: "x86_64-unknown-linux-gnu"
        required: false
        type: string      
      artifact_name:
        description: "Name of the GH action artifact to upload"
        default: "cargo-ui-linux"
        required: false
        type: string
      qt_version:
        description: "Qt version to install"
        default: "5.15.2"
        required: false
        type: string

jobs:
  build_cargo_ui_binary:
    name: Build a single cargo-ui binary
    runs-on: ${{ inputs.host_os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ github.event.inputs.rust_target }}
      # Only needed for the GL Backend
      - name: Install Linux Dependencies
        if: github.event.inputs.host_os == 'ubuntu-latest'
        run: sudo apt-get install libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v2
        with:
          path: ~/work/sixtyfps/Qt
          key: ${{ runner.os }}-${{ github.job }}-Qt
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ github.event.inputs.qt_version }}
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          arch: win64_mingw81 # Only used on Windows
      - uses: Swatinem/rust-cache@v1            
      - name: Build
        uses: actions-rs/cargo@v1
        with:
            command: build
            args: --verbose --target ${{ github.event.inputs.rust_target }} --release
      - id: binary-name        
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            echo "::set-output name=binary-name::cargo-ui.exe"
          else
            echo "::set-output name=binary-name::cargo-ui"
          fi
        shell: bash
      - name: Create artifact directory
        run: |
            mkdir bin
            cp target/${{ github.event.inputs.rust_target }}/release/${{ steps.binary-name.outputs.binary-name }} bin/${{ steps.binary-name.outputs.binary-name }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
            name: ${{ github.event.inputs.artifact_name }}
            path: |
                bin

